export default {
	at: '2023-03-05T09:56:29.084Z',
	products: [
		{
			description: 'fugiat labore magna reprehenderit',
			name: 'officia',
			price: 343.3,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{},
		{},
		{},
		{},
		{
			description: 'sunt veniam esse excepteur',
			name: 'laborum',
			price: 1037.67,
			tmpProperty: undefined,
			activePromoId: 80,
		},
		{},
		{},
		{
			description: 'laborum id excepteur ipsum',
			name: 'amet',
			price: 240,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{},
		{},
		{},
		{},
		{},
		{},
		{
			description: 'tempor ut adipisicing anim',
			name: 'labore',
			price: 366.85,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'qui ex tempor eiusmod',
			name: 'qui',
			price: 916.11,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'dolor aute qui qui',
			name: 'velit',
			price: 166.66,
			tmpProperty: undefined,
			activePromoId: 98,
		},
		{
			description: 'tempor excepteur velit sunt',
			name: 'mollit',
			price: 639.52,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'et elit nostrud ipsum',
			name: 'do',
			price: 1557.53,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'commodo duis magna commodo',
			name: 'adipisicing',
			price: 926.26,
			tmpProperty: undefined,
			activePromoId: 68,
		},
		{
			description: 'cupidatat exercitation laborum laborum',
			name: 'incididunt',
			price: 349.11,
			tmpProperty: undefined,
			activePromoId: 88,
		},
		{
			description: 'est nulla aliqua nostrud',
			name: 'officia',
			price: 878.73,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'voluptate sunt eiusmod exercitation',
			name: 'eiusmod',
			price: 1766.38,
			tmpProperty: undefined,
			activePromoId: 77,
		},
		{
			description: 'Lorem occaecat nisi labore',
			name: 'exercitation',
			price: 579.73,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'irure do adipisicing dolore',
			name: 'excepteur',
			price: 639.71,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'occaecat excepteur amet anim',
			name: 'nisi',
			price: 1792.66,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'ullamco eiusmod ut eu',
			name: 'enim',
			price: 1997.86,
			tmpProperty: undefined,
			activePromoId: 94,
		},
		{
			description: 'magna tempor culpa non',
			name: 'cillum',
			price: 1673.52,
			tmpProperty: undefined,
			activePromoId: 74,
		},
		{
			description: 'non ut nostrud enim',
			name: 'aute',
			price: 633.37,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'ad culpa irure elit',
			name: 'aliquip',
			price: 660.37,
			tmpProperty: undefined,
			activePromoId: 81,
		},
		{
			description: 'laborum sunt laborum reprehenderit',
			name: 'magna',
			price: 1603.17,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'ullamco fugiat ea do',
			name: 'in',
			price: 831.52,
			tmpProperty: undefined,
			activePromoId: 28,
		},
		{
			description: 'exercitation excepteur non culpa',
			name: 'fugiat',
			price: 570.21,
			tmpProperty: undefined,
			activePromoId: 35,
		},
		{
			description: 'consectetur dolore dolore nisi',
			name: 'quis',
			price: 1777.49,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'do ea aute est',
			name: 'sunt',
			price: 581.59,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'voluptate commodo veniam aute',
			name: 'ut',
			price: 1614.71,
			tmpProperty: undefined,
			activePromoId: 83,
		},
		{
			description: 'qui culpa est deserunt',
			name: 'et',
			price: 1576.48,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'cupidatat est occaecat occaecat',
			name: 'reprehenderit',
			price: 1802.9,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'nisi id eiusmod labore',
			name: 'voluptate',
			price: 533.23,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'deserunt labore ad ea',
			name: 'mollit',
			price: 376.73,
			tmpProperty: undefined,
			activePromoId: 14,
		},
		{
			description: 'in amet incididunt elit',
			name: 'magna',
			price: 1635.75,
			tmpProperty: undefined,
			activePromoId: 67,
		},
		{
			description: 'do tempor incididunt ea',
			name: 'ea',
			price: 1260.13,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'veniam enim officia laborum',
			name: 'ut',
			price: 241.78,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'ut cillum labore ut',
			name: 'aute',
			price: 1738.32,
			tmpProperty: undefined,
			activePromoId: 95,
		},
		{
			description: 'minim proident qui incididunt',
			name: 'aute',
			price: 996.55,
			tmpProperty: undefined,
			activePromoId: 30,
		},
		{
			description: 'aute nostrud officia fugiat',
			name: 'reprehenderit',
			price: 146.35,
			tmpProperty: undefined,
			activePromoId: 25,
		},
		{
			description: 'amet enim consectetur dolor',
			name: 'labore',
			price: 180.58,
			tmpProperty: undefined,
			activePromoId: 50,
		},
		{
			description: 'velit magna tempor id',
			name: 'voluptate',
			price: 1188.6,
			tmpProperty: undefined,
			activePromoId: 20,
		},
		{
			description: 'quis officia pariatur eu',
			name: 'officia',
			price: 1435.85,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'consequat adipisicing fugiat esse',
			name: 'officia',
			price: 1614.96,
			tmpProperty: undefined,
			activePromoId: 82,
		},
		{
			description: 'cillum exercitation cupidatat irure',
			name: 'duis',
			price: 1381.61,
			tmpProperty: undefined,
			activePromoId: 17,
		},
		{
			description: 'adipisicing laborum commodo eu',
			name: 'id',
			price: 427.37,
			tmpProperty: undefined,
			activePromoId: 30,
		},
		{
			description: 'nisi do ad nisi',
			name: 'aliquip',
			price: 1054.66,
			tmpProperty: undefined,
			activePromoId: 10,
		},
		{
			description: 'laboris nostrud magna occaecat',
			name: 'amet',
			price: 331.27,
			tmpProperty: undefined,
			activePromoId: 91,
		},
		{
			description: 'magna amet ad deserunt',
			name: 'non',
			price: 1154.56,
			tmpProperty: undefined,
			activePromoId: 55,
		},
		{
			description: 'pariatur officia elit deserunt',
			name: 'laborum',
			price: 1697.67,
			tmpProperty: undefined,
			activePromoId: 36,
		},
		{
			description: 'dolor non aliquip dolor',
			name: 'ea',
			price: 263.97,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'tempor laborum consequat voluptate',
			name: 'esse',
			price: 298.46,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'ipsum magna laborum officia',
			name: 'magna',
			price: 1713.23,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'nisi dolor cillum in',
			name: 'culpa',
			price: 1942.73,
			tmpProperty: undefined,
			activePromoId: 69,
		},
		{
			description: 'nisi excepteur eu laborum',
			name: 'eu',
			price: 867.52,
			tmpProperty: undefined,
			activePromoId: 64,
		},
		{
			description: 'ipsum proident cillum incididunt',
			name: 'elit',
			price: 454.48,
			tmpProperty: undefined,
			activePromoId: 6,
		},
		{
			description: 'exercitation anim ut eu',
			name: 'deserunt',
			price: 1898.24,
			tmpProperty: undefined,
			activePromoId: 12,
		},
		{
			description: 'excepteur minim nisi nulla',
			name: 'anim',
			price: 695.75,
			tmpProperty: undefined,
			activePromoId: 71,
		},
		{
			description: 'nostrud laboris Lorem elit',
			name: 'ea',
			price: 1422.84,
			tmpProperty: undefined,
			activePromoId: 81,
		},
		{
			description: 'culpa tempor commodo culpa',
			name: 'elit',
			price: 1121.57,
			tmpProperty: undefined,
			activePromoId: 52,
		},
		{
			description: 'adipisicing deserunt irure ad',
			name: 'ea',
			price: 1524.9,
			tmpProperty: undefined,
			activePromoId: 46,
		},
		{
			description: 'nisi consectetur excepteur cupidatat',
			name: 'laboris',
			price: 682.53,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'tempor culpa amet velit',
			name: 'commodo',
			price: 1600.94,
			tmpProperty: undefined,
			activePromoId: 21,
		},
		{
			description: 'dolor et culpa excepteur',
			name: 'do',
			price: 670.12,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'cillum ex minim est',
			name: 'ex',
			price: 1056.97,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'laboris duis in dolore',
			name: 'aliquip',
			price: 1932.64,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'ullamco tempor magna proident',
			name: 'quis',
			price: 1401.79,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'minim sint voluptate cillum',
			name: 'veniam',
			price: 1396.56,
			tmpProperty: undefined,
			activePromoId: 76,
		},
		{
			description: 'eu aute deserunt ut',
			name: 'tempor',
			price: 1519.09,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'tempor pariatur aliqua consectetur',
			name: 'sit',
			price: 1858.77,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'laboris nulla aliqua et',
			name: 'nostrud',
			price: 340.88,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'labore enim aliqua ex',
			name: 'mollit',
			price: 735.58,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'eiusmod voluptate nulla eiusmod',
			name: 'non',
			price: 368.57,
			tmpProperty: undefined,
			activePromoId: 24,
		},
		{
			description: 'dolor fugiat culpa aute',
			name: 'pariatur',
			price: 1788.96,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'sint consectetur cillum magna',
			name: 'incididunt',
			price: 443.09,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'ullamco ex nisi irure',
			name: 'adipisicing',
			price: 268.52,
			tmpProperty: undefined,
			activePromoId: 0,
		},
		{
			description: 'et incididunt elit nisi',
			name: 'veniam',
			price: 1346.27,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'laboris tempor ea veniam',
			name: 'aute',
			price: 1564.41,
			tmpProperty: undefined,
			activePromoId: 89,
		},
		{
			description: 'nostrud incididunt proident sunt',
			name: 'labore',
			price: 1285.99,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'ullamco aute non minim',
			name: 'occaecat',
			price: 1737.79,
			tmpProperty: undefined,
			activePromoId: 53,
		},
		{
			description: 'quis aliquip cillum culpa',
			name: 'id',
			price: 1222.07,
			tmpProperty: undefined,
			activePromoId: 99,
		},
		{
			description: 'tempor sunt amet sint',
			name: 'eu',
			price: 373.28,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'minim duis sit cillum',
			name: 'eu',
			price: 1705.92,
			tmpProperty: undefined,
			activePromoId: 31,
		},
		{
			description: 'cillum fugiat mollit ad',
			name: 'dolor',
			price: 1960.38,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'duis pariatur veniam ex',
			name: 'consequat',
			price: 1510.18,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'amet velit aliqua laboris',
			name: 'tempor',
			price: 1905.53,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'aute aliqua minim cupidatat',
			name: 'cillum',
			price: 1694.43,
			tmpProperty: undefined,
			activePromoId: 38,
		},
		{
			description: 'consectetur fugiat in consequat',
			name: 'occaecat',
			price: 963.15,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'consectetur esse culpa nisi',
			name: 'ut',
			price: 959.44,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'Lorem ipsum eiusmod cillum',
			name: 'et',
			price: 1992.88,
			tmpProperty: undefined,
			activePromoId: 95,
		},
		{
			description: 'in esse id ut',
			name: 'nulla',
			price: 1905.02,
			tmpProperty: undefined,
			activePromoId: 7,
		},
		{
			description: 'ea incididunt ipsum ipsum',
			name: 'laboris',
			price: 147.16,
			tmpProperty: undefined,
			activePromoId: 91,
		},
		{
			description: 'voluptate exercitation est labore',
			name: 'enim',
			price: 1130.21,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'tempor voluptate consequat quis',
			name: 'id',
			price: 851.1,
			tmpProperty: undefined,
			activePromoId: 85,
		},
		{
			description: 'cillum enim qui consectetur',
			name: 'aute',
			price: 1147.57,
			tmpProperty: undefined,
			activePromoId: 0,
		},
		{
			description: 'non et proident laboris',
			name: 'consequat',
			price: 508.39,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'cillum reprehenderit ut excepteur',
			name: 'officia',
			price: 1100.64,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'labore amet Lorem nulla',
			name: 'excepteur',
			price: 857.09,
			tmpProperty: undefined,
			activePromoId: 98,
		},
		{
			description: 'deserunt consectetur non sit',
			name: 'id',
			price: 839.39,
			tmpProperty: undefined,
			activePromoId: 40,
		},
		{
			description: 'aliqua et qui mollit',
			name: 'commodo',
			price: 1071.52,
			tmpProperty: undefined,
			activePromoId: 18,
		},
		{
			description: 'non nisi in labore',
			name: 'tempor',
			price: 1869.7,
			tmpProperty: undefined,
			activePromoId: 23,
		},
		{
			description: 'sit cupidatat cupidatat veniam',
			name: 'reprehenderit',
			price: 718.75,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'ea irure voluptate pariatur',
			name: 'ipsum',
			price: 811.6,
			tmpProperty: undefined,
			activePromoId: null,
		},
		{
			description: 'consectetur ipsum reprehenderit anim',
			name: 'velit',
			price: 311.72,
			tmpProperty: undefined,
			activePromoId: 86,
		},
		{
			description: 'quis reprehenderit ullamco et',
			name: 'nisi',
			price: 437.39,
			tmpProperty: undefined,
			activePromoId: 28,
		},
	],
};
